export {default as HeaderProgram} from './HeaderProgram'
export {default as DescriptionProgram} from './DescriptionProgram'
export {default as SectionPhrase} from './SectionPhrase'
export {default as SectionDetails} from './SectionDetails'
export {default as CardDetailProgram} from './CardDetailProgram'
export {default as SectionImageDescription} from './SectionImageDescription'
export {default as CardLeftImageDescription} from './CardLeftImageDescription'
export {default as CardRigthImageDescription} from './CardRigthImageDescription'