export { default as FoundersSection } from './FoundersSection'
export { default as CardFounder } from './CardFounder'
export { default as VolunteersSection} from './VolunteersSection'
export { default as CardVolunteer} from './CardVolunteer'
export {default as CategoryVolunteer} from './CategoryVolunteer'
export { default as LifeSection } from './LifeSection'
export { default as CardLife } from './CardLife'